### ISSUE TITLE
OAuth token is missing

### ISSUE THREAD

**Issue by 4a-42** [DumpsterDoofus/ReChatDownloader#7]
I seem to have authorization error

```ps1
PS C:\Tools\TwitchChatDownloader\publish> dotnet .\TwitchChatDownloader.dll video --videoid 915834024
[12:43:52 INF] Getting info for video ID: 915834024
[12:43:52 ERR] Timestamp: 02/19/2021 12:43:52 Type: Response Resource: https://api.twitch.tv/helix/videos?id=915834024 Statuscode: 401 Elapsed: 162 ms Content: {"error":"Unauthorized","status":401,"message":"OAuth token is missing"}

Something really bad happened. Application shutting down.
TwitchLib.Api.Core.Exceptions.BadScopeException: Your request was blocked due to bad credentials (Do you have the right scope for your access token?).
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at TwitchChatDownloader.Implementations.VideoRetriever.GetVideo(Int32 videoId) in D:\Software\My Software\Twitch-Chat-Downloader\TwitchChatDownloader\Implementations\VideoRetriever.cs:line 26
   at CSharpFunctionalExtensions.AsyncResultExtensionsLeftOperand.OnSuccess[T](Task`1 resultTask, Action`1 action)
   at CSharpFunctionalExtensions.AsyncResultExtensionsLeftOperand.OnFailure[T](Task`1 resultTask, Action`1 action)
   at CSharpFunctionalExtensions.AsyncResultExtensionsBothOperands.OnSuccess[T](Task`1 resultTask, Func`2 action)
   at TwitchChatDownloader.TwitchChatDownloader.Process(VideoOptions options) in D:\Software\My Software\Twitch-Chat-Downloader\TwitchChatDownloader\TwitchChatDownloader.cs:line 23
   at TwitchChatDownloader.Program.Main(String[] args) in D:\Software\My Software\Twitch-Chat-Downloader\TwitchChatDownloader\Program.cs:line 27
```

**Comment by 4a-42** [comment]
When I build the application from source, it works but when I use the published release, it doesn't.

**Comment by illusdidi** [comment]
i got the same error message

**Comment by jet082** [comment]
Even having built from source it does not work.

**Comment by shadowkhas** [comment]
Seconding - looks like Twitch removing v5 API support broke it.
